project:
  type: website
  output-dir: docs

resources: 
  - CNAME

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "Blog"
  site-url: https://eisenra.github.io/the_raph_round-up/
  description: "My personal blog"
  navbar:
    left:
      - About.qmd
      - Photography.qmd
      - Shop.qmd
      - AI_statement.qmd
      # - text: "Photography"
      #   menu:
      #     - Wildilfe.qmd
      #     - Landscape.qmd
    right:
      - icon: camera
        href: https://www.flickr.com/photos/202433373@N03/
      - icon: mastodon
        href: https://genomic.social/@EisenRa
      - icon: linkedin
        href: https://www.linkedin.com/in/raphael-eisenhofer-499b5a84/
      - icon: github
        href: https://github.com/EisenRa
      - icon: rss
        href: index.xml
  comments:
      giscus: 
        repo: EisenRa/the_raph_round-up
        mapping: "pathname"
        reactions-enabled: true
        input-position: "bottom"
        theme: "light"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    
    css: styles.css
    include-after-body: subscribe.html
    
execute:
  freeze: auto
  
editor: visual

